### ISSUE TITLE
List files in buckets

### ISSUE THREAD

**Issue by jyecusch** [nitrictech/nitric#225]
It would be useful to list files in a bucket so they can be created by another process or indexed.

e.g.

```javascript
const things = bucket('things').for('reading')
const files: File[] = await things.files()
```

Do we need/should we have another permission to enable listing?

**Comment by tjholm** [comment]
should listing files have its own permission type in the SDK?.

At the moment File listing is it's own action in our proto contracts:
https://github.com/nitrictech/nitric/blob/develop/contracts/proto/resource/v1/resource.proto (see `BucketFileList`).
