### ISSUE TITLE
GCP - Cloud Run Gateway incorrectly deserialized nitric events.

### ISSUE THREAD

**Issue by tjholm** [nitrictech/nitric#243]
Nitric event are fully placed in the event trigger as the payload rather than being separated.

**Comment by asalkeld** [comment]
@tjholm  fixed by this: https://github.com/nitrictech/nitric/commit/e7b96f00ecae194d51c1e8fbc4e8f2a225f139e6 ?

**Comment by raksiv** [comment]
Does this require a re-test?
