### ISSUE TITLE
Create issue template - nitric repo, cli and node sdk projects

### ISSUE THREAD

**Issue by raksiv** [nitrictech/nitric#248]

**Comment by raksiv** [comment]
This is a design exercise, not implementation.
There is already contained in these templates which need review and minor adjustments.

**Comment by raksiv** [comment]
Add a note about requesting the user to run the debug command, and paste the content into the issue.

**Comment by elisselockhart** [comment]
New copy for the bug report and feature request templates [here](https://docs.google.com/document/d/1z0-rXXDE0o_Z6yhfzbigexOhQ11I9cK4QXehUDciehU/edit#heading=h.3czx7s22oeh).

Relies on the new diagnostic command in #155.

**Comment by raksiv** [comment]
Requires a user with access to the 'settings' tab in git to update the issues template.

**Comment by raksiv** [comment]
Test for consistency across all projects.
