### ISSUE TITLE
Function storage triggers

### ISSUE THREAD

**Issue by tjholm** [nitrictech/nitric#270]
**Describe the solution you'd like**
The ability to trigger a function based on storage events, such as uploading or deleting of files on a bucket.

**Why is this needed? What challenge will it help you solve? Please describe.**

Processing files from blob events on sucessful upload or change/deletion is a very common workflow with some use cases being:
 - File optimization on upload (e.g. images).
 - Asynchronous processing of user submissions (reacting to a user uploading a file for processing).

**Describe alternatives you've considered**

Current alternatives would be to use queues and and a schedule with a fixed cadence for file processing. This would be fine for workloads that can be batch processed, but a direct trigger will be needed where more reactive processing is required. The batch processing alternative would also result in wasted compute time where no items are present to process.

**Comment by jyecusch** [comment]
Released
