### ISSUE TITLE
Retrieve runtime API metadata

### ISSUE THREAD

**Issue by raksiv** [nitrictech/nitric#308]
SDK and API operation to retrieve the following:

- Resource name
- Resource ID (e.g. ARN in AWS)
- URL

**Comment by tjholm** [comment]
See proposal at:
https://github.com/nitrictech/nitric/pull/330

**Comment by tjholm** [comment]
Implemented and tested in node-sdk. Once in should be testable with nitric deploy as well (there may be some permissions issues from the CLI that need to be sorted out).
