### ISSUE TITLE
Support triggering functions from resources such as queues and buckets (maybe others)

### ISSUE THREAD

**Issue by raksiv** [nitrictech/nitric#314]
**Describe the solution you'd like**

We've received feedback that developers would like to trigger functions from queues and buckets.

**Why is this needed? What challenges will it help you solve? Please describe.**

Real-time processing of buckets and items which enter queues are supported features in AWS, developers are familiar with this practice or may want to migrate code verbatim from their existing implementations without re-architecture work.

**Describe alternatives you've considered**

It is possible to accomplish the same goals using events and/or using scheduled jobs for batch processing in some cases.

**Comment by tjholm** [comment]
Let's break this down into smaller design tickets.

I remember the original thinking was to implement a general system for handling all as CloudEvents, but we could also implement dedicated worker types for each of these event types for routing as well.

**Comment by tjholm** [comment]
Broken down into new issues
