### ISSUE TITLE
Project process Environment Variables not available on AWS scheduled jobs

### ISSUE THREAD

**Issue by mal-drop** [nitrictech/nitric#328]
### Issue
Process env variables are not available to schedule jobs on AWS.

For example:

```javascript
import { schedule } from "@nitric/sdk";

const backupSchedule = schedule('run-a-backup').every(
    '1 hours',
    async (ctx) => {
        console.info(`MONDAY_ENDPOINT: ${process.env.MONDAY_ENDPOINT}`);
    }
);
```

The AWS logs show the environment variable MONDAY_ENDPOINT as undefined:

```
...
START RequestId: 7ac2652d-0b7e-4604-94fe-d2c7d8842458 Version: $LATEST
2022-09-17T13:00:23.388+10:00 | MONDAY_ENDPOINT: undefined
END RequestId: 7ac2652d-0b7e-4604-94fe-d2c7d8842458
...
REPORT RequestId: 7ac2652d-0b7e-4604-94fe-d2c7d8842458	Duration: 755.50 ms	Billed Duration: 1204 ms	Memory Size: 128 MB	Max Memory Used: 93 MB	Init Duration: 447.81 ms	
```

Please see the project:

https://deploy.nitric.io/dropbio-test/typescript-starter/settings/environment-variables

**Comment by jyecusch** [comment]
Hey @mal-drop I'm assuming you set the env variables via the Deploy UI. If so, did you redeploy your application after making the changes? Currently, env variables are only updated during a build operation.

![image](https://user-images.githubusercontent.com/4121391/190935657-b5d9cee8-080e-436b-a8fc-4d9c6cb0fc9f.png)

> The note is subtle, we should probably improve that

If you did that and it's still not working let me know and we'll take a look
