### ISSUE TITLE
Distributed tracing

### ISSUE THREAD

**Issue by jyecusch** [nitrictech/nitric#329]
### Suggestion

Investigate the best approach to provide automatic inclusion of distributed tracing in the framework. What tools and standards already exist that we should use/integrate with/support?

### Value

Tracing in distributed systems is useful to fully understand the impact of a request and identify issues, bottlenecks or perform debugging.

### Alternatives

The current option is to implement your own solution, but we've had several requests to provide out of the box support for this since it's such a common need.

**Comment by tjholm** [comment]
https://opentelemetry.io/
