### ISSUE TITLE
Go Support

### ISSUE THREAD

**Issue by jyecusch** [nitrictech/nitric#340]
Updating Go support in the Nitric Framework, including SDK, Template(s) and Docs.

General language support checklist:

- [x] Language SDK, with IfC support and doc comments
- [x] Languages specific examples documented
- [x] Language/SDK reference docs
- [x] Language template
- [x] Works in Nitric Deploy

**Comment by asalkeld** [comment]
sdk godocs: https://github.com/nitrictech/go-sdk/pull/70
template: https://github.com/nitrictech/templates/pull/3
