### ISSUE TITLE
Small Typo in BYO Database Docs

### ISSUE THREAD

**Issue by pulpdood** [nitrictech/nitric#386]
### Page 
BYO Database documentation on the nitric docs: https://nitric.io/docs/guides/byo-database

### Issue
The PostgreSQL section talks about using a postgres driver to connect to MySQL. I think it's a typo.

### Suggestion
Change MySQL to PostgreSQL.

### Other info
![image](https://user-images.githubusercontent.com/13587944/221491326-ddd10419-df9a-4a2d-88c3-c0ca90c4f804.png)

**Comment by raksiv** [comment]
Thanks @pulpdood , I've created a PR to resolve this. Will close when merged.

**Comment by jyecusch** [comment]
Fixed in public docs
