### ISSUE TITLE
Lambda provisioned concurrency support

### ISSUE THREAD

**Issue by jyecusch** [nitrictech/nitric#401]
We'd like to update the default AWS provider to support provisioned concurrency configuration in stack files. This will enable further mitigation of cold start latency during changes in load to handlers deployed to Lambda.

**Comment by tjholm** [comment]
Implemented as part of: https://github.com/nitrictech/nitric/pull/404

**Comment by tjholm** [comment]
Available in latest dev version of nitric providers.
