### ISSUE TITLE
Unclear error when nitric up conflicts with nitric start

### ISSUE THREAD

**Issue by HomelessDinosaur** [nitrictech/nitric#407]
When an instance of the membrane is running (through Nitric start or otherwise) and deployment is started, an undefined error is provided:
```
rpc error: code = Unimplemented desc = unknown service nitric.deploy.v1.DeployService
```
Can fix the issue by stopping the current instance of Nitric.

**Comment by tjholm** [comment]
We should fix this with dynamic port allocation for the new providers (via ENV) and have the CLI client connect to this rather than the default

**Comment by tjholm** [comment]
https://github.com/nitrictech/nitric/pull/412
