### ISSUE TITLE
Support multiple instance on local Nitric Server

### ISSUE THREAD

**Issue by nyomansunima** [nitrictech/nitric#493]
### Suggestion

Allow the nitric server to run multiple project on the local machine.

### Value

Sometimes we need to develop multiple project on the local machine. eg. Microservices, small projects update and so on. However for now nitric server can only run on single instance on the local computer. But if we can add the multiple instance support to running on local, it will add more ability to enhance this project.

Here are some benefits that may be consider
- 🤖 Allow running multiple project at one. (For example we have multiple service as backend)
- 🏀 Allow nitric become more reliable for development

### Alternatives

- Make monorepo an manage using single nitric configs, then use handlers to manage multiple trigger.
- Allow another instance to running on local machine

### Other info

<img width="1023" alt="Screenshot 2023-08-09 at 09 40 13" src="https://github.com/nitrictech/nitric/assets/54091887/90a558ce-0a46-4d7e-b4c6-893a256ef288">

**Comment by jyecusch** [comment]
Released in v1
