### ISSUE TITLE
Allow to invoke multiple Functions using Single API Gateway

### ISSUE THREAD

**Issue by nyomansunima** [nitrictech/nitric#494]
### Suggestion

The main concept here is one of the great options to implement **Microservices**. This will allow user to access multiple function without worry about combine multiple REST API. The user can combine multiple function to only produce on single API.

### Value

- Manage multiple api with single access url to the public
- When building heavy backend the user don't confused to combine multiple api that produces multiple functions
- When the user want to leverage the server and service, they can automatically run on Microservices.

### Alternatives

- Use single api() then combine multiple path, think like express router.
- Create a new API Gateway and add invoke manually

### Other info

https://onehwengineer.com/aws-api-gateway-invoke-lambda/

**Comment by tjholm** [comment]
Hi @nyomansunima if I'm understanding your requirement, this should already be the case for Nitric `api`.

I've got an example of how this works here, the infrastructure will be two lambdas connected to a shared API Gateway.
https://github.com/nitrictech/example-apps/tree/microservices/microservices/typescript

Nitric resources declared with the same name will be considered the same resources even if they're declared in two different functions/services:

For example

```typescript
// function-one.ts
import { api } from "@nitric/sdk";

const publicApi = api('public');

publicApi.get('/hello/:name', async () => {
   // your logic here
})
```

```typescript
// function-two.ts
import { api } from "@nitric/sdk";

const publicApi = api('public');

publicApi.get('/goodbye/:name', async () => {
   // your logic here
})
```
> We encourage adding shared resources like this into a new module as I've done in the linked [example](https://github.com/nitrictech/example-apps/tree/microservices/microservices/typescript).

This currently does not apply to `http` at the moment, so with external frameworks they will each be proxied by their own gateway (more of a monolith). We're still working on this feature though and may look changing how this works.

Let me know if that helps.

**Comment by nyomansunima** [comment]
@tjholm Now thanks for help me!
