### ISSUE TITLE
Update Docs  when use nitric in Github Actions

### ISSUE THREAD

**Issue by nyomansunima** [nitrictech/nitric#495]
### Page 

https://nitric.io/docs/guides/getting-started/github-actions

### Issue

When i try to implement the code in my personal projects. i found that i getting error `provider nitric/aws** is not supported', so i check my local machine than i found the solutions

### Suggestion

Change the version from `1.2.1` to the latest version which is `1.28.0`

**Comment by tjholm** [comment]
This has now been released :smile:
