### ISSUE TITLE
cli: improve new stack command DX

### ISSUE THREAD

**Issue by jyecusch** [nitrictech/nitric#506]
Update DX and prompts in the `nitric stack new` command. Let's update it to match the new DX of the new project command, with clear prompts for each step and inline input validation to minimize errors causing a restart of the process.

**Comment by davemooreuws** [comment]
last few things:

- [ ] prevent the pulumi login state check, this isnt required for creating a stack file
- [ ] create the vhs tapes

**Comment by davemooreuws** [comment]
More context:

The current output is inconsistent, the output has mixed letter casing and while the provider says "which do you wish.." the region said "select" when they're both dropdown selections. I think we could make some small changes to improve this output.

Current:

```
nitric stack new
? What do you want to call your new stack? dev
? Which Cloud do you wish to deploy to? aws
? select the region us-east-1
```

Suggest updating to something consistent:

```
nitric stack new
? What do you want to name this stack? dev
? Which provider do you want to deploy with? aws
? Which region should the stack deploy to? us-east-1
```

or something concise:

```
nitric stack new
? Stack name: dev
? Provider: aws
? Region: us-east-1
```

**Comment by davemooreuws** [comment]
Once we decide and implement this we should update relevant docs/examples where we can.

**Comment by davemooreuws** [comment]
docs are here: https://github.com/nitrictech/docs/pull/488
