### ISSUE TITLE
Lock down pulumi plugin versions for providers

### ISSUE THREAD

**Issue by tjholm** [nitrictech/nitric#515]
Currently providers don't enforce the plugin versions they're using leading to deployments failing when new users automatically get the latest resource plugins if an older version wasn't already present.

We should lock down the plugin versions at least to a known working major version to avoid being impacted by breaking changes made in Pulumi's resource plugins.

**Comment by davemooreuws** [comment]
We have seen this recently with the docker plugin from pulumi.

**Comment by tjholm** [comment]
Address by: https://github.com/nitrictech/nitric/pull/526
