### ISSUE TITLE
Document standard env variables

### ISSUE THREAD

**Issue by jyecusch** [nitrictech/nitric#519]
There are a set of standard env variables (e.g. NITRIC_STACK_ID) which should be documented, including the level of reliance developers can place on them (i.e. will they change in future).

**Comment by jyecusch** [comment]
this will be impacted by https://github.com/nitrictech/nitric/pull/514 which changes the standard StackID env var name for clarity.

**Comment by davemooreuws** [comment]
Good example: https://vercel.com/docs/projects/environment-variables/system-environment-variables#system-environment-variables

**Comment by davemooreuws** [comment]
Variables to document:

Nitric specific:
```
NITRIC_STACK_ID: coolkat-gcp-4c0wg0hg
NITRIC_ENVIRONMENT: cloud, ... etc
```

Cloud specific:
```
GCP_REGION: 
```

**Comment by davemooreuws** [comment]
Closed by: https://github.com/nitrictech/docs/pull/487
