### ISSUE TITLE
`for()` or equivalent is possible in some SDKs

### ISSUE THREAD

**Issue by jyecusch** [nitrictech/nitric#524]
### Issue

When requesting resource permissions it's possible to leave the parameters blank, this is not highlighted as an error in code editors due to use of a variadic input.

e.g. `topic('example').for()`

An error isn't thrown until deployment, which in a larger project could take a little more effort to narrow down.

![blank-for-error](https://github.com/nitrictech/nitric/assets/4121391/a95983cc-8158-4e34-bb16-a25bcea1eef0)

### Expected

The error is highlighted inline, indicating that you're missing a required parameter. This should be possible by having the `for` methods accept a single permission followed by the variadic, forcing '1 or more' as a requirement.

**Comment by tjholm** [comment]
Progress on this:

- [ ] Node
- [ ] Python
- [ ] Go
- [ ] JVM
- [ ] C#
