### ISSUE TITLE
Dart Support

### ISSUE THREAD

**Issue by chimon2000** [nitrictech/nitric#546]
### Suggestion
Support for the Dart language and ecosystem: being able to build applications with Nitric using the Dart language.

### Value
Dart and Flutter have dominated the cross-platform market share for several years, but Dart is a multiplatform language that can be used both for client applications and the backend. Unfortunately, there is not a good story around cloud development since most IaC SDKs do not support Dart. 

### Alternatives
Write IaC in a non-Dart language or write the backend in another language, which increases the complexity of the application since the client will always be Dart.

Use a Vercel clone like Globe.dev that abstracts away the infrastructure and handles the IaC. This solution can be inflexible as you scale because you are limited to the choices of Globe.dev.

### Other info
n/a

**Comment by tjholm** [comment]
Dart SDK for nitric v1 has been released:
https://pub.dev/packages/nitric_sdk
