### ISSUE TITLE
SQL Database Support

### ISSUE THREAD

**Issue by jyecusch** [nitrictech/nitric#608]
Enable nitric applications to define a 'database' resource, which will be deployed/imported and configured like other nitric cloud resources. Given database abstraction is a problem with many existing solutions (SQL, ORMs, etc.) nitric will not provide an abstraction over the underlying resource (unlike with other nitric resources). Instead, the resource will provide connection details at runtime.

**Comment by tjholm** [comment]
Initial AWS RDS support here:
https://github.com/nitrictech/nitric/pull/613

**Comment by HomelessDinosaur** [comment]
https://github.com/nitrictech/nitric/pull/623

**Comment by jyecusch** [comment]
Azure Support here:
https://github.com/nitrictech/nitric/pull/631
