### ISSUE TITLE
Azure - deploy the code to already existing "resource group" without creating a new one

### ISSUE THREAD

**Issue by JustAndrew-pixel** [nitrictech/nitric#646]
### Suggestion

Add a parameter in config `.yaml` for deploying the code to already existing "resource group".

### Value

As a user with an Azure account provided by my company, but without admin rights I'm not able to create a new "resource group" before deploying the code. But a have an already created "resource group" by my admin assigned to my acc. In that case I'd like to have a config parameter to define in which resource group my code should be deployed. If that parameter is not defined, a new resource group must be created when deploying.

### Other info

![image](https://github.com/user-attachments/assets/2461b429-b2eb-4c98-a514-baefa5158e48)

**Comment by jyecusch** [comment]
This makes sense to me. We'll need to verify this won't cause conflicts or name collisions if two projects/stacks are configured with the same existing resource group, if it does we'll need to look for a workaround.

**Comment by tjholm** [comment]
have raised: https://github.com/nitrictech/nitric/pull/648

Will need to do some testing with it. Most of the resources we deploy should be appended with random identifiers that should prevent them from conflicting within the same resource group, but we'll do some testing with multiple stacks to see if we come up against any limitations.

**Comment by tjholm** [comment]
released in v1.11.0 https://github.com/nitrictech/nitric/releases/tag/v1.11.0
