### ISSUE TITLE
Error deleting GCP database subnetwork

### ISSUE THREAD

**Issue by HomelessDinosaur** [nitrictech/nitric#667]
When deleting a stack that has been deployed with a SQL database on GCP the following error occurs:

```
Error when reading or editing Subnetwork: googleapi: Error 400: The subnetwork resource 'projects/example/regions/australia-southeast1/subnetworks/nitric-db-subnetwork' is already being used by 'projects/example/regions/australia-southeast1/addresses/serverless-ipv4-1721014303789269923'
```

The stack can only be destroyed after GCP cleans up its address reservation, which can take a couple of hours. This seems to be a problem with GCP, as it's impossible to delete the stack manually using the gcloud CLI or the portal.

Related issues:
- https://discuss.hashicorp.com/t/gcp-delete-automatic-created-resources-not-by-terraform/28749
- https://stackoverflow.com/questions/78524117/failed-to-release-serverless-ipv4-because-in-use-by-some-address-reservation
- https://cloud.google.com/knowledge/kb/unable-to-delete-project-due-to-ghost-subnetwork-and-instance-000004625

**Comment by jyecusch** [comment]
Resolved by: https://github.com/nitrictech/nitric/pull/623
