### ISSUE TITLE
Podman support

### ISSUE THREAD

**Issue by jyecusch** [nitrictech/nitric#691]
### Suggestion

Support Nitric and the Nitric CLI using Podman

### Value

Allows people using Podman instead of Docker to also use Nitric

### Alternatives

Use Docker, but this isn't always an option

### Notes

The issue surfaces as a CLI error message:
"error Docker daemon is not running, please start the docker daemon and try again"

**Comment by GeraldLoeffler** [comment]
for licensing reasons, I must use Podman at work. Hence I ran into this issue, on Apple Silicon.

I can offer to test any proposed solution on that setup.

(There is an additional complication that I'm also behind an explicit web proxy, so use env vars like HTTP_PROXY, HTTPS_PROXY, NO_PROXY), but let's hope that "just works" with Nitric. Anyway, I regularly use Podman in that environment without issues - with the exception of Nitric.)

**Comment by tjholm** [comment]
PRs raised for this:
https://github.com/nitrictech/nitric/pull/695
https://github.com/nitrictech/cli/pull/815

**Comment by tjholm** [comment]
merged

**Comment by tjholm** [comment]
Released in:

https://github.com/nitrictech/nitric/releases/tag/v1.15.5

and

https://github.com/nitrictech/cli/releases/tag/v1.55.2

**Comment by jyecusch** [comment]
If you're using TypeScript you'll also need the Docker template from the latest example project https://github.com/nitrictech/examples/tree/main/v1/typescript-starter (see the `nitric.yaml` file and the dockerfile). The updated dockerfile removes a cache feature that's no supported by podman.
