### ISSUE TITLE
Local/Dev Membrane expects /nitric directory at root.

### ISSUE THREAD

**Issue by jyecusch** [nitrictech/nitric#71]
Instead of defaulting to `/nitric` for local run we should get the directory location from config (env or cli arg). Perhaps the default should be `~/.nitric` for safety on local machines outside of a container? @tjholm?

┆Issue is synchronized with this [Clickup task](https://app.clickup.com/t/1dyn9mz) by [Unito](https://www.unito.io)

**Comment by tjholm** [comment]
Agreed, at the moment each of the individual directories are configurable for each plugin that uses the file system, but these should be relative to a shared home directory configured by an environment variable.

**Comment by nanikjava** [comment]
Looking at the code the `plugins/kv/dev/kv.go` code is reading the env variable `LOCAL_DB_DIR` and fallback to `/nitric`.

Would be more useful something like 

`membrane --db-dir=/some/directory` ?
